### ISSUE TITLE
feat: Mount ~/.aws/credentials from secret

### ISSUE THREAD

**Issue by yuliyantsvetkov** [cloudquery/helm-charts#350]
### Are you positive this feature should be implemented in the Helm Chart?

- [X] I'm positive this is an Helm Chart feature

### Which problem is this feature request solving?

I would like to mount AWS **access** and **security** **keys** profiles under the `~/.aws/credentials` file from **Kubernetes secret** in order to be able to use them inside the `aws` plugin `local_profile` variable.

### Describe the solution you'd like

This can be solved by adding additional mount volume to the `container` of the `cronJob` resource which is `read-only` and read from **Kubernetes secret**.

### Pull request (optional)

- [X] I can submit a pull request
```[tasklist]
### Tasks
- [x] Add values configuration parameters
- [x] Test the helm chart
- [ ] Test the cloudquery binary with `aws` source plugin
```

**Comment by yuliyantsvetkov** [comment]
I have created this **issue** for my self, but I cannot assign it to me. Will send a PR in the upcoming hours or a day.

**Comment by yuliyantsvetkov** [comment]
That is actually achievable via updating the `volumes` and the `volumeMounts` like that in the `helm-chart`, but for some reason **Cloudquery** does not pick up the profiles.

Here is the `YAML` that can be easily documented:

```
# Optional. Additional volumes to mount in the pod.
volumes:
- name: aws-credentials-secrets
  secret:
    secretName: aws-credentials-secrets
# Optional. Additional volumes to mount in the pod.
volumeMounts:
- name: aws-credentials-secrets
  mountPath: /root/.aws/credentials
  subPath: credentials
```

And the file is successfully mounted to the container in the proper place.

Still debugging why it does not pick them up in the `source` AWS plugin like that:

```
  # AWS XXXXXXXXX
  kind: source
  spec:
    name: development_aws
    path: cloudquery/aws
    version: "v22.0.1"
    tables: ["aws_s3_buckets"]
    spec:
      regions:
        - "*"
      accounts:
        - id: "someaccount"
          local_profile: "XXXXXXXXXX"
```

**Comment by yuliyantsvetkov** [comment]
The `cloudquery/s3` plugin does not have `accounts` configuration, and unfortunately requires to have the `AWS_PROFILE` env. variable to be exported to the container. For this reason `destinationS3` account can be added to the values files of the **helm-chart**.

Since the scope of this issue has been closed with the previous comment, and no commits are required, I am closing this issue.

**Comment by erezrokah** [comment]
Thanks for reporting back with the solution @yuliyantsvetkov
